List<Map<String,dynamic>> hcpAddressFields = [
  {
    "fieldNumber": 0,
    "fieldType" : "parameter",
    "fieldName" : "userName",
    "dataEntryType": "",
    "canBeEntered" : false,
    "shouldBeShown" : false,
    "isRequired": false,
    "minLength" : 0,
    "maxLength" : 0,
    "regExValidator": "",
    "groupId": "00",
    "readOnly": false,
    "textController": "",
    "defaultValue": "",
    "isConstructed": false,
    "constructionFields": [],
  },
{
"fieldNumber": 1,
"fieldType" : "ObjectId",
"fieldName" : "_id",
"dataEntryType": "",
"canBeEntered" : false,
"shouldBeShown" : false,
"isRequired": false,
"minLength" : 0,
"maxLength" : 0,
"regExValidator": "",
"groupId": "00",
"readOnly": true,
"textController": "",
"defaultValue": "",
"isConstructed": false,
"constructionFields": [],
},
  {
    "fieldNumber": 2,
    "fieldType" : "int",
    "fieldName" : "hcpId",
    "dataEntryType": "",
    "listName": "",
    "canBeEntered" : false,
    "isRequired": true,
    "minLength" : 0,
    "maxLength" : 0,
    "regExValidator": "",
    "groupId": "00",
    "readOnly": true,
    "textController": "fieldController02",
    "defaultValue" : "",
  "isConstructed": false,
  "constructionFields": [],
  },
{
  "fieldNumber": 3,
  "fieldType" : "int",
  "fieldName" : "addressId",
  "dataEntryType": "",
  "listName": "",
  "canBeEntered" : false,
  "isRequired": false,
  "minLength" : 0,
  "maxLength" : 0,
  "regExValidator": "",
  "groupId": "00",
  "readOnly": true,
  "textController": "fieldController03",
  "defaultValue" : "",
  "isConstructed": false,
  "constructionFields": [],
},
  {
    "fieldNumber": 4,
    "fieldType" : "int",
    "fieldName" : "addressTypeCodeId",
    "dataEntryType": "dropdown",
    "listName": "addressType",
    "canBeEntered" : true,
    "isRequired": true,
    "minLength" : 0,
    "maxLength" : 0,
    "regExValidator": "",
    "groupId": "01",
    "readOnly": false,
    "textController": "fieldController04",
    "defaultValue" : "",
    "isConstructed": false,
    "constructionFields": [],
  },
  {
    "fieldNumber": 5,
    "fieldType" : "String",
    "fieldName" : "addressType",
    "dataEntryType": "field",
    "listName": "addressType",
    "canBeEntered" : true,
    "isRequired": true,
    "minLength" : 0,
    "maxLength" : 0,
    "regExValidator": "",
    "groupId": "01",
    "readOnly": false,
    "textController": "fieldController05",
    "defaultValue": "",
    "isConstructed": false,
    "constructionFields": [],
  },
  {
    "fieldNumber": 6,
    "fieldType" : "String",
    "fieldName" : "addressLine1",
    "dataEntryType": "field",
    "listName": "",
    "canBeEntered" : true,
    "isRequired": false,
    "minLength" : 1,
    "maxLength" :  32,
    "regExValidator": "",
    "groupId": "",
    "readOnly": false,
    "textController": "fieldController06",
    "defaultValue": "",
    "isConstructed": false,
    "constructionFields": [],
  },
  {
    "fieldNumber": 7,
    "fieldType" : "String",
    "fieldName" : "addressLine2",
    "dataEntryType": "field",
    "listName": "",
    "canBeEntered" : true,
    "isRequired": false,
    "minLength" : 1,
    "maxLength" : 32,
    "regExValidator": "",
    "groupId": "",
    "readOnly": false,
    "textController": "fieldController07",
    "defaultValue": "",
    "isConstructed": false,
    "constructionFields": [],
  },
  {
    "fieldNumber": 8,
    "fieldType" : "String",
    "fieldName" : "city",
    "dataEntryType": "field",
    "listName": "",
    "canBeEntered" : true,
    "isRequired": true,
    "minLength" : 1,
    "maxLength" : 32,
    "regExValidator": "",
    "groupId": "",
    "readOnly": false,
    "textController": "fieldController08",
    "defaultValue" : "",
    "isConstructed": false,
    "constructionFields": [],
  },
  {
    "fieldNumber": 9,
    "fieldType" : "String",
    "fieldName" : "state",
    "dataEntryType": "dropdown",
    "listName": "stateCodes",
    "canBeEntered" : true,
    "isRequired": true,
    "minLength" : 4,
    "maxLength" : 32,
    "regExValidator": "",
    "groupId": "",
    "readOnly": false,
    "textController": "fieldController09",
    "defaultValue": "",
    "isConstructed": false,
    "constructionFields": [],
  },
  {
    "fieldNumber": 10,
    "fieldType" : "String",
    "fieldName" : "zipCode",
    "dataEntryType": "field",
    "listName": "",
    "canBeEntered" : true,
    "isRequired": true,
    "minLength" : 5,
    "maxLength" : 5,
    "regExValidator": "allNumeric",
    "groupId": "",
    "readOnly": false,
    "textController": "fieldController10",
    "defaultValue": "",
    "isConstructed": false,
    "constructionFields": [],
  },
  {
    "fieldNumber": 11,
    "fieldType" : "bool",
    "fieldName" : "isPrimary",
    "dataEntryType": "checkbox",
    "listName": "",
    "canBeEntered" : true,
    "isRequired": true,
    "minLength" : 1,
    "maxLength":  1,
    "regExValidator": "",
    "groupId": "",
    "readOnly": false,
    "textController": "fieldController11",
    "defaultValue": false,
    "isConstructed": false,
    "constructionFields": [],
  },
  {
    "fieldNumber": 12,
    "fieldType" : "bool",
    "fieldName" : "isPaycheck",
    "dataEntryType": "checkbox",
    "listName": "",
    "canBeEntered" : true,
    "isRequired": true,
    "minLength" : 1,
    "maxLength":  1,
    "regExValidator": "",
    "groupId": "",
    "readOnly": false,
    "textController": "fieldController12",
    "defaultValue": false,
    "isConstructed": false,
    "constructionFields": [],
  },
  {
    "fieldNumber": 13,
    "fieldType" : "String",
    "fieldName" : "fullAddress",
    "dataEntryType": "field",
    "listName": "",
    "canBeEntered" : false,
    "isRequired": false,
    "minLength" : 10,
    "maxLength":  200,
    "regExValidator": "",
    "groupId": "",
    "readOnly": false,
    "textController": "",
    "defaultValue": "",
    "isConstructed": true,
    "constructionFields": [0,6,7,8,9,10.13,14,17],
  },
  {
    "fieldNumber": 14,
    "fieldType" : "String",
    "fieldName" : "county",
    "dataEntryType": "field",
    "listName": "",
    "canBeEntered" : true,
    "isRequired": false,
    "minLength" : 10,
    "maxLength":  32,
    "regExValidator": "",
    "groupId": "",
    "readOnly": false,
    "textController": "fieldController14",
    "defaultValue": "",
    "isConstructed": false,
    "constructionFields": []
  },
  {
    "fieldNumber": 15,
    "fieldType" : "double",
    "fieldName" : "latitude",
    "dataEntryType": "field",
    "listName": "",
    "canBeEntered" : true,
    "isRequired": false,
    "minLength" : 0,
    "maxLength":  0,
    "regExValidator": "",
    "groupId": "",
    "readOnly": false,
    "textController": "fieldController15",
    "defaultValue": "",
    "isConstructed": false,
    "constructionFields": []
  },
  {
    "fieldNumber": 16,
    "fieldType" : "double",
    "fieldName" : "longitude",
    "dataEntryType": "field",
    "listName": "",
    "canBeEntered" : true,
    "isRequired": false,
    "minLength" : 0,
    "maxLength":  0,
    "regExValidator": "",
    "groupId": "",
    "readOnly": false,
    "textController": "fieldController16",
    "defaultValue": "",
    "isConstructed": false,
    "constructionFields": []
  },
  {
    "fieldNumber": 17,
    "fieldType" : "String",
    "fieldName" : "country",
    "dataEntryType": "field",
    "listName": "",
    "canBeEntered" : true,
    "isRequired": false,
    "minLength" : 10,
    "maxLength":  32,
    "regExValidator": "",
    "groupId": "",
    "readOnly": false,
    "textController": "fieldController17",
    "defaultValue": "",
    "isConstructed": false,
    "constructionFields": []
  },
];

List<Map<String,dynamic>> getAddresstemplate() {
  return hcpAddressFields;
  
}