// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    print('line 22 $FirebaseOptions $defaultTargetPlatform $ios');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
         return macos;
        //  throw UnsupportedError(
        //    'DefaultFirebaseOptions have not been configured for macos - '
        //        'you can reconfigure this by running the FlutterFire CLI again.',
        // );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmz32bgud4YpSqbdPGh-HFoVKdrv_vqnQ',
    appId: '1:146420810693:web:7531e00f3b0da4c36001ac',
    messagingSenderId: '146420810693',
    projectId: 'cmsproject-8e245',
    authDomain: 'cmsproject-8e245.firebaseapp.com',
    storageBucket: 'cmsproject-8e245.appspot.com',
    measurementId: 'G-T0JJJ894CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0GGmSfA2a6a0VI5-P_B5_ZUFjuTBDg9U',
    appId: '1:146420810693:android:0d14ec982b22c2f36001ac',
    messagingSenderId: '146420810693',
    projectId: 'cmsproject-8e245',
    storageBucket: 'cmsproject-8e245.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAesGc04QhMfobwT7X2l6XOIxL6DEtteA8',
    appId: '1:146420810693:ios:317840b536c7f7a46001ac',
    messagingSenderId: '146420810693',
    projectId: 'cmsproject-8e245',
    storageBucket: 'cmsproject-8e245.appspot.com',
    iosBundleId: 'com.cms.client.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAesGc04QhMfobwT7X2l6XOIxL6DEtteA8',
    appId: '1:146420810693:ios:b613b95ac4c06e846001ac',
    messagingSenderId: '146420810693',
    projectId: 'cmsproject-8e245',
    storageBucket: 'cmsproject-8e245.appspot.com',
    iosBundleId: 'com.cms.client.app.macos',
  );


  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmz32bgud4YpSqbdPGh-HFoVKdrv_vqnQ',
    appId: '1:146420810693:web:0204761cd4c851276001ac',
    messagingSenderId: '146420810693',
    projectId: 'cmsproject-8e245',
    authDomain: 'cmsproject-8e245.firebaseapp.com',
    storageBucket: 'cmsproject-8e245.appspot.com',
    measurementId: 'G-0SKK4V9ZM9',
  );
}
