// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0GGmSfA2a6a0VI5-P_B5_ZUFjuTBDg9U',
    appId: '1:146420810693:android:56e6d7b4e2e09fd86001ac',
    messagingSenderId: '146420810693',
    projectId: 'cmsproject-8e245',
    storageBucket: 'cmsproject-8e245.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAesGc04QhMfobwT7X2l6XOIxL6DEtteA8',
    appId: '1:146420810693:ios:2299b9f97a69dc8d6001ac',
    messagingSenderId: '146420810693',
    projectId: 'cmsproject-8e245',
    storageBucket: 'cmsproject-8e245.appspot.com',
    iosBundleId: 'com.cmsios.hcp.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAesGc04QhMfobwT7X2l6XOIxL6DEtteA8',
    appId: '1:146420810693:ios:c40b7296eb0319526001ac',
    messagingSenderId: '146420810693',
    projectId: 'cmsproject-8e245',
    storageBucket: 'cmsproject-8e245.appspot.com',
    iosBundleId: 'com.cms.hcpApp',
  );

}